name: tripman
description: tripman.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.6
  mask_text_input_formatter: ^2.4.0
  meta: ^1.9.1
  page_transition: ^2.0.9
  pinput: ^2.2.31
  restart_app: ^1.2.1
  shimmer: ^3.0.0
  simple_animations: ^5.0.0+3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
